databases:
  - name: sorayi4_b4t
    databaseName: sorayi4_b4t
    user: sorayia_admin

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn SorayiaAPI.wsgi:application --bind 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SorayiaAPI
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4