# Generated by Django 4.2.7 on 2024-01-23 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 21, 50, 51, 890933)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 21, 50, 51, 887739)),
        ),
    ]
