# Generated by Django 4.2.7 on 2024-01-24 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bot_created_at_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 1, 34, 31, 541340)),
        ),
        migrations.AddField(
            model_name='chat',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 1, 34, 31, 542293)),
        ),
        migrations.AddField(
            model_name='file',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 1, 34, 31, 538858)),
        ),
        migrations.AddField(
            model_name='folder',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 1, 34, 31, 541840)),
        ),
        migrations.AddField(
            model_name='message',
            name='update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 1, 34, 31, 539274)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 1, 34, 31, 536973)),
        ),
    ]
