# Generated by Django 4.2.7 on 2024-01-30 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_folder_bot_folders_remove_bot_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 18, 27, 55, 390721)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 18, 27, 55, 391849)),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 18, 27, 55, 392983)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 18, 27, 55, 390151)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 18, 27, 55, 392464)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 18, 27, 55, 375262)),
        ),
    ]
