# Generated by Django 4.2.7 on 2024-02-04 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bot_created_at_alter_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bot',
            name='split_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 18, 47, 57, 637607)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 18, 47, 57, 639226)),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 18, 47, 57, 640966)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 18, 47, 57, 636874)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 18, 47, 57, 640119)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 18, 47, 57, 615988)),
        ),
    ]
