# Generated by Django 4.2.7 on 2024-02-04 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bot_description_bot_split_url_alter_bot_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avatar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 19, 25, 21, 96305)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 19, 25, 21, 97447)),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 19, 25, 21, 98572)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 19, 25, 21, 95794)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 19, 25, 21, 98073)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 19, 25, 21, 81108)),
        ),
    ]
