# Generated by Django 4.2.7 on 2024-03-01 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_chat_name_alter_bot_created_at_alter_chat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(related_name='chat_messages', to='app.message'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 3, 16, 17, 234789)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 3, 16, 17, 235962)),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 3, 16, 17, 237520)),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 3, 16, 17, 234038)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 3, 16, 17, 237010)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 3, 16, 17, 231930)),
        ),
    ]
